# Generated by Django 4.2.4 on 2023-10-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_room_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(max_length=100)),
                ('main_message', models.CharField(max_length=1000000)),
                ('user_remarks', models.CharField(max_length=1000000)),
            ],
        ),
    ]
