# Generated by Django 4.2.3 on 2023-10-17 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_errorreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_message',
            field=models.CharField(default='Nothing to say', max_length=10000000),
        ),
    ]
