# Generated by Django 4.2.4 on 2023-10-27 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_message_reply_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorreport',
            name='users_original_message',
            field=models.CharField(default=' ', max_length=1000000),
        ),
    ]
