# Generated by Django 4.2.4 on 2023-10-27 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_errorreport_users_original_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='errorreport',
            name='main_message',
        ),
        migrations.AddField(
            model_name='errorreport',
            name='main_reply',
            field=models.CharField(default=' ', max_length=1000000),
        ),
    ]
